# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name mydstn
#' @title Discrete Sine Transform (DST-II)
#' @description Computes the Discrete Sine Transform (DST-II) of a numeric vector.
#' @param input A numeric vector of type `Eigen::VectorXd`.
#' @param Ns Integer. The size of the input vector.
#' @return A numeric vector representing the transformed values.
#' @examples
#' input <- c(1, 2, 3, 4)
#' result <- mydstn(input, length(input))
NULL

#' @name DST_Solver
#' @title DST Solver Function
#' @description Solves a system using the Discrete Sine Transform (DST-II) and scaling.
#' @param Dim Integer. The dimension of the problem.
#' @param Lambda A numeric vector of scaling factors.
#' @param B A sparse matrix used in the solver.
#' @param U A numeric vector representing the initial state.
#' @param Ns Integer. The size of the segments processed by DST.
#' @return A numeric vector of the normalized result.
#' @examples
#' Lambda <- c(1, 2, 3, 4)
#' result <- DST_Solver(1, Lambda, diag(Lambda), c(1, 2, 3, 4), 4)
NULL

DST_Solver <- function(Dim, Lambda, B, U, Ns) {
  .Call(`_YauYauFilter_DST_Solver`, Dim, Lambda, B, U, Ns)
}

#' @name ExpandGrid
#' @title Generate a Grid of All Combinations of Input Sequence
#' @description Generates a grid by expanding an input sequence across dimensions.
#' @param Dim Integer. The number of dimensions.
#' @param s A numeric vector representing the input sequence.
#' @return A numeric matrix where each row is a combination of the input values.
#' @examples
#' s <- c(1, 2, 3)
#' grid <- ExpandGrid(2, s)
#' print(grid)
NULL

ExpandGrid <- function(Dim, s) {
  .Call(`_YauYauFilter_ExpandGrid`, Dim, s)
}

#' @name NormalizedExp
#' @title Normalized Exponential Function
#' @description Computes a normalized exponential of a numeric vector to avoid overflow.
#' @param x A numeric vector to process.
#' @return A numeric vector with normalized exponential values summing to 1.
#' @examples
#' x <- c(1, 2, 3, 4)
#' result <- NormalizedExp(x)
NULL

NormalizedExp <- function(x) {
  .Call(`_YauYauFilter_NormalizedExp`, x)
}

#' @name Simulate_State_Obser
#' @title Simulate State and Observations
#' @description Simulates the state trajectory and observations for a dynamical system.
#' @param Dt Numeric. The time step size.
#' @param Ntau Integer. Number of observation points.
#' @param NtNtau Integer. Total number of time steps.
#' @param f A user-defined function for state dynamics.
#' @param h A user-defined function for observations.
#' @param Dim Integer. The number of dimensions.
#' @param seed Nullable Integer. Optional random seed for reproducibility.
#' @return A list with the state trajectory, observations, and random seed used.
#' @examples
#' f <- function(x) x * 0.1
#' h <- function(x) x + 0.5
#' result <- Simulate_State_Obser(0.01, 10, 100, f, h, 2, seed = 123)
NULL

Simulate_State_Obser <- function(Dt, Ntau, NtNtau, f, h, Dim, seed = NULL) {
  .Call(`_YauYauFilter_Simulate_State_Obser`, Dt, Ntau, NtNtau, f, h, Dim, seed)
}

#' @name computeB
#' @title Compute Matrix B
#' @description Computes matrix B using sparse Kronecker products and user-defined functions.
#' @param s A numeric matrix of grid points.
#' @param D_list A list of sparse matrices for differential operators.
#' @param Dt Numeric. Time step size.
#' @param Ds Numeric. Grid spacing.
#' @param f A user-defined function for transformations.
#' @param df A derivative function.
#' @param h A function contributing to diagonal updates.
#' @return A sparse matrix representing the computed matrix B.
#' @examples
#' D_list <- list(Diagonal(4), Diagonal(4))
#' result <- computeB(matrix(1:8, 4, 2), D_list, 0.01, 0.5, sin, cos, function(x) x^2)
NULL

computeB <- function(s, D_list, Dt, Ds, f, df, h) {
  .Call(`_YauYauFilter_computeB`, s, D_list, Dt, Ds, f, df, h)
}

#' @name computeLambda
#' @title Compute Lambda Vector
#' @description Computes the Lambda vector for discretized Laplacian eigenvalues.
#' @param Dim Integer. The number of dimensions.
#' @param Ns Integer. The grid size in each dimension.
#' @param Dt Numeric. Time step size.
#' @param Ds Numeric. Space step size.
#' @return A numeric vector of scaled eigenvalues.
#' @examples
#' result <- computeLambda(3, 4, 0.01, 0.5)
NULL

computeLambda <- function(Dim, Ns, Dt, Ds) {
  .Call(`_YauYauFilter_computeLambda`, Dim, Ns, Dt, Ds)
}

#' @name kroneckerProduct
#' @title Compute Kronecker Product of Sparse Matrices
#' @description Computes the Kronecker product of two sparse matrices.
#' @param A A sparse matrix.
#' @param B A sparse matrix.
#' @return A sparse matrix representing the Kronecker product of A and B.
#' @examples
#' library(Matrix)
#' A <- Diagonal(4)
#' B <- Diagonal(4)
#' result <- kroneckerProduct(A, B)
NULL

#' @name generateD
#' @title Generate Sparse Matrices Using Kronecker Products
#' @description Generates a list of sparse matrices for differential operators in high-dimensional grids.
#' @param Dim Integer. The number of dimensions.
#' @param Ns Integer. The grid size in each dimension.
#' @param Ds Numeric. The grid spacing.
#' @return A list of sparse matrices representing differential operators.
#' @examples
#' result <- generateD(3, 4, 0.5)
NULL

generateD <- function(Dim, Ns, Ds) {
  .Call(`_YauYauFilter_generateD`, Dim, Ns, Ds)
}
